- hosts: app
  vars:
    root_dir: /usr/share/nginx/html
    nginx_port: 80
    magic_name: "This is server {{ ansible_hostname }}!"
  tasks:
    - name: install
      ansible.builtin.apt:
        name:
          - nginx
          - cowsay
        state: latest
        update_cache: yes
      become: yes

    - name: cowsay
      ansible.builtin.command: "cowsay '{{ magic_name }}'"
      register: result

    - name: update nginx config
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{root_dir}}/index.html"
      notify:
        - restart nginx
      become: yes

    - name: update nginx config
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
