- hosts: app
  gather_facts: no
  vars:
    users:
      - one
      - two
      - three
  tasks:
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      become: yes

    - name: add users
      ansible.builtin.include_role:
        name: userenv
      vars:
        userenv_user_name: "{{ item }}"
        userenv_user_password: "123"
        userenv_user_email: "{{ item }}@example.com"
      loop: "{{ users }}"
      tags: [add_user]

    - name: setup ssh authorized keys
      ansible.posix.authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', 'files/id_rsa.pub') }}"
      loop: "{{ users }}"
      become: yes